### PR TITLE
Added an example for enabling the QSPI flash and onboard SD card slot of a Grand Central M4

### PR DESCRIPTION
**Pull request by DrItanium**
I tried to make it as succinct as possible. This sketch runs successfully on a Grand Central M4.

### CODE REVIEW

**Comment by DrItanium** [comment]
I have modified and tested the example using a metro m4 and metro m0.

**Comment by hathach** [comment]
look great, thank you, could you mind rename the example to `SdFat_Flash_and_SDcard` to make it clearer. The SdFat is a library name, other example such as SdFat_ReadWrite means read write to flash using SdFat and has nothing to do with SDcard. I know the name is not perfect, but at least it make it super clear.

**Comment by DrItanium** [comment]
I actually struggled with the name of this example. I like your suggestion a heck of a lot more! :)

**Review by hathach — APPROVED** [review]
GetSDcardPin() can be a define. But this is just minor. Thank you for the pr

**Review by hathach — APPROVED** [review]
GetSDcardPin() can be a define. But this is just minor. Thank you for the pr

**Comment by DrItanium** [comment]
Its marked constexpr. It will do the same thing as a define but enforce
type checking.

**Pull request merged**
