### PR TITLE
first artifact

### PR DESCRIPTION
**Pull request by ladyada**

### CODE REVIEW

**Comment by ladyada** [comment]
@dhalbert can you test any/some of the artifacts for the PR work to erase flash (and blink the neopixel LED)

**Review by hathach — APPROVED** [review]
Everything look great, though considering the amount of `.board.generate` file, maybe we should update the ci-arduino script to read the contents of single file `.generate` with a list of boards instead. It probably make thing easier to maintain. If you agree I could help to update the ci-arduino.

PS: The existing way (.board.generate) of course can continue to work as it is as well.

**Comment by ladyada** [comment]
for now i actually prefer it this way, even tho i know it is very manual. thank you :)

**Comment by ladyada** [comment]
ok i tested this with metro m0 and pyportal

**Comment by dhalbert** [comment]
I will also be testing on a few boards.

**Review by dhalbert — APPROVED** [review]
Tested on:
Metro ESP32-S2
Feather RP2040
Feather nRF52840

I tried to pick platforms you had not tried.

erased CIRCUITPY successfully on all of these; came back fresh after reloading CPy afterwards

**Comment by ladyada** [comment]
@dhalbert ok thanks! you can have the forum person try the pyportal titano eraser - once we do a release here we can update the troubleshooting page to point to the release zip so it can be up-to-date

**Pull request merged**
